### ISSUE TITLE
with ant design not work

### ISSUE THREAD

**Issue by seantech2000** [PlasmoHQ/examples#17]
error:
`$ plasmo dev
🟣 Plasmo v0.56.0
🟠 The browser extension development framework.
🔵 INFO   | Starting the extension development server...
🔴 ERROR  | Inline JavaScript is not enabled. Is it set in your options?`
plasmo version : 0.56.0

**Comment by louisgv** [comment]
Can't reproduce on my end. Are you using the exact setup in our example,? Also please file the issue in the framework repo instead, thanks!
