### ISSUE TITLE
Using pnpm install find no matching version error

### ISSUE THREAD

**Issue by KingWu** [PlasmoHQ/examples#25]
Node: 16.17.0
pnpm: 6.14.7

No matching version found for @plasmohq/prettier-plugin-sort-imports@* inside the workspace

**Comment by louisgv** [comment]
You will need to use pnpm@7 to install the dependency. This example directory cannot be used by itself, it's mainly for reference purposes.

See: https://discord.com/channels/946290204443025438/1044558522316234752

Also please see #8
