### ISSUE TITLE
getMountPoint supprot document.querySelectorAll API

### ISSUE THREAD

**Issue by deno-source** [PlasmoHQ/examples#3]
Hello, dear open source author.  I encountered a difficult requirement in development.  We need to embed the same button on each DOM in a list of goods, but getMountPoint does not currently support multiple DOM elements.  My current approach is to use TS to write native scripts.

**Comment by ColdSauce** [comment]
Hi @deno-source, thanks for the feature request! That makes sense! We'll add something to help you out soon.

**Comment by louisgv** [comment]
@deno-source moved the discussion to https://github.com/PlasmoHQ/plasmo/issues/22 - We're moving the issue tracker for this repository into https://github.com/PlasmoHQ/plasmo/ :D
