### ISSUE TITLE
Improve the example with-ant-design(add style injection for content script UI)

### ISSUE THREAD

**Issue by zangguojun** [PlasmoHQ/examples#4]
use `D - Optional style container, injected into the shadowDOM`  in `RFC | Style injection for Content Script UI #9`
add `contents/index.tsx`
```
import { Button } from "antd"
import cssText from "data-text:~/index.css"
import type { PlasmoContentScript } from "plasmo"

export const config: PlasmoContentScript = {
  matches: ["https://space.bilibili.com/*"]
}

export const getStyle = () => {
  const style = document.createElement("style")
  style.textContent = cssText
  return style
}

const Index = () => {
  return (
    <div
      style={{
        position: "fixed",
        top: "50%"
      }}>
      <Button type="primary">Hello Ant Design</Button>
    </div>
  )
}

export default Index
```
Maybe you also should upgrade your plasmo verison.

**Comment by ColdSauce** [comment]
Thanks for the suggestion! If you submit a pull request, I will merge it with these changes

**Comment by louisgv** [comment]
@zangguojun  moved the discussion to https://github.com/PlasmoHQ/plasmo/issues/23 - We're moving the issue tracker for this repository into https://github.com/PlasmoHQ/plasmo/ :D
